#!/bin/bash

if ! source plon.shm; then
	echo 'error: plon.shm not found in $PATH'
	exit 255
fi

MISSING=$(plon_check_progs ntfsresize awk) \
	|| { echo_error "error: $MISSING not found"; exit 1; }

[ $# -eq 1 ] \
	|| { echo_error "usage $PLON_0 device" ; exit 2; }

[ -b "$1" ] \
	|| { echo_error "error: $DEV is not a block device"; exit 3; }

DEV="$1"
PARTSIZE=$(ntfsresize -i "$DEV" | grep '^Current device size' | awk '{print $4}')
[ plon_is_numeric "$PARTSIZE" ] || { echo_error "error: unable to get partition size"; exit 4; }

ntfsresize -f -s "$PARTSIZE" "$DEV"

